import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx=vm.createContext({module:{exports:{}}});vm.runInContext(fs.readFileSync(new URL('./sorami-history.js',import.meta.url),'utf8'),ctx);const H=ctx.module.exports;
const p=(i=0)=>({name:`場所${i}`,latitude:35+i/1000,longitude:139,eyeHeightAGL:151.5,decks:[{name:'展望台',aglM:150}],terrain:'summit'});
function fixture(){let data=null,fail=false,clock=0;const h=H.create({read:()=>data,write:(_,v)=>{if(fail)return false;data=JSON.parse(JSON.stringify(v));return true;},now:()=>++clock,validatePlan:x=>x?.kind==='aim'&&x.t&&x.o?JSON.parse(JSON.stringify(x)):null});return {h,data:()=>data,fail:x=>fail=x};}
test('recent places are capped, deduplicated, preserve viewing height and do not expose arbitrary fields',()=>{const {h}=fixture();for(let i=0;i<35;i++)h.add('places',{...p(i),password:'do not retain',junk:{a:1}});assert.equal(h.list('places').length,30);assert.equal(h.list('places')[0].value.name,'場所34');h.add('places',p(10));assert.equal(h.list('places').length,30);const v=h.list('places')[0].value;assert.equal(v.eyeHeightAGL,151.5);assert.equal(v.decks[0].aglM,150);assert.equal(v.password,undefined);assert.equal(v.junk,undefined);});
test('reject malformed coordinates and imported entries',()=>{assert.equal(H.place({...p(),latitude:91}),null);assert.equal(H.place({...p(),name:'a\n'}),null);const h=H.create({read:()=>({places:[{usedAt:1,value:{...p(),longitude:181}},{usedAt:'bad',value:p()}],plans:[]}),write:()=>true,validatePlan:()=>null});assert.equal(h.list('places').length,0);});
test('failed save and deletion retain the previous stored list, and clear can be undone',()=>{const f=fixture();f.h.add('places',p());f.fail(true);assert.equal(f.h.add('places',p(1)),false);assert.equal(f.h.clear('places'),false);assert.equal(f.h.remove('places',0),false);assert.equal(f.h.list('places').length,1);f.fail(false);assert.equal(f.h.clear('places'),true);assert.equal(f.h.list('places').length,0);assert.equal(f.h.restore(),true);assert.equal(f.h.list('places')[0].value.name,'場所0');});
test('same day conditions update time and focal length, different target/body/place/date stay separate',()=>{const {h}=fixture();const v={kind:'aim',t:{id:'tower'},o:['撮影地',35,139,0,1.5,null],body:'moon',part:'tip',limb:'center',at:Date.UTC(2027,8,17,9),l:{focal:400}};h.add('plans',v);h.add('plans',{...v,at:v.at+60000,l:{focal:500}});assert.equal(h.list('plans').length,1);assert.equal(h.list('plans')[0].value.l.focal,500);for(const x of [{body:'sun'},{t:{id:'fuji'}},{o:['別地点',36,139,0,1.5,null]},{at:v.at+86400000}])h.add('plans',{...v,...x});assert.equal(h.list('plans').length,5);assert.equal(h.remove('plans',1),true);assert.equal(h.restore(),true);assert.equal(h.list('plans').length,5);});

test('history and undo remain isolated across account/guest scopes, without deleting either history',()=>{let owner='A',clock=0;const values=new Map();const h=H.create({scope:()=>owner,read:k=>values.get(k),write:(k,v)=>{values.set(k,JSON.parse(JSON.stringify(v)));return true;},now:()=>++clock,validatePlan:()=>null});h.add('places',p(1));h.clear('places');assert.equal(h.canUndo(),true);owner='B';assert.equal(h.canUndo(),false);assert.equal(h.restore(),false);assert.equal(h.list('places').length,0);h.add('places',p(2));owner='A';assert.equal(h.restore(),true);assert.equal(h.list('places')[0].value.name,'場所1');owner='B';assert.equal(h.list('places')[0].value.name,'場所2');owner='guest';assert.equal(h.list('places').length,0);});
test('deletion follows the clicked identity after another tab changes ordering',()=>{const {h}=fixture();h.add('places',p(1));h.add('places',p(2));const clicked=h.list('places')[1];h.add('places',p(3));assert.equal(h.remove('places',clicked),true);assert.deepEqual(Array.from(h.list('places'),r=>r.value.name),['場所3','場所2']);});
test('direct condition restore uses the same heights/lens/date and does not embed history in the route',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),start=html.indexOf('function restoreSharedPlan('),end=html.indexOf('function initPlanSharing()',start);const els=new Map();const configured=[];const aim={limbsByBody:{},candPick:3,wantSpot:'old',wantKey:'old',reverse:{}},lens={},air={};const p={kind:'aim',body:'moon',limb:'onTop',part:'tip',t:{id:'tower',name:'塔',latitude:35,longitude:139,groundM:10,parts:[{id:'tip',name:'頂部',m:100}]},o:['展望台',35,139,20,151.5,null],at:Date.UTC(2027,8,17,9,4),pan:[.1,.2],l:{on:true,focal:426.9,sensor:'full',portrait:true,grid:'thirds'},air:'none'};const c=vm.createContext({planRestoredFragment:null,location:{hash:'#/aim'},SoramiBodies:{definition:()=>({})},SoramiAlign:{targetById:()=>null,CITY_MODELS:{}},SoramiPlan:{expandPoint:o=>({name:o[0],latitude:o[1],longitude:o[2]})},aim,aimLens:lens,aimAirSettings:air,aimAirSync(){},aimAirSeq:0,aimAirLoadKey:'old',aimAirCompare:{at:0},aimCal:{seq:0,cache:new Map()},aimRidgeCache:new Map(),SoramiAtmosphere:{configure:mode=>configured.push(mode)},store:{set(){}},aimSavedFrom:x=>x,$:id=>{if(!els.has(id))els.set(id,{});return els.get(id);}});vm.runInContext(html.slice(start,end),c);c.restoreSharedPlan(p);assert.equal(aim.body,'moon');assert.equal(aim.limb,'onTop');assert.equal(els.get('aimLimb').innerHTML,'');assert.equal(aim.candPick,null);assert.equal(aim.wantSpot,null);assert.equal(aim.reverse,null);assert.equal(c.aimAirCompare,null);assert.deepEqual(configured,['none']);assert.equal(aim.from.groundManualM,20);assert.equal(aim.from.standAglM,151.5);assert.equal(aim.pendingPlan.at,p.at);assert.equal(lens.focal,426.9);assert.equal(lens.portrait,true);assert.equal(els.get('aimDate').value,'2027-09-17');assert.equal(c.location.hash,'#/aim');assert.match(aim.from.subtitle,/履歴/);});

test('derived automatic place visits do not erase searched address, decks or manual observation height',()=>{const {h}=fixture();h.add('places',{...p(),subtitle:'東京都の展望台',stand:'展望台',standAglM:151.5,groundManualM:22});h.add('places',{name:'短い名前',latitude:35,longitude:139,subtitle:'最近使った撮影地',eyeHeightAGL:151.5},{derived:true});const v=h.list('places')[0].value;assert.equal(v.name,'場所0');assert.equal(v.subtitle,'東京都の展望台');assert.equal(v.decks[0].aglM,150);assert.equal(v.groundManualM,22);assert.equal(v.standAglM,151.5);});

test('base-place choice cannot unblock an old custom observer; explicit aim observer can',()=>{const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),start=html.indexOf('function choosePlace('),end=html.indexOf('/// 地点の画面を道具',start);let observer;const c=vm.createContext({placeSheetFor:null,aim:{from:{latitude:36,longitude:140}},recentHistory:{rememberPlace:(p,o)=>observer=o.observer},PLACE_PICKERS:{aim:{set(){}}},selectPlace(){},$(){return{close(){}}},aimAreaOf:()=>''});vm.runInContext(html.slice(start,end),c);c.choosePlace(p());assert.equal(observer,false);c.aim.from=null;c.choosePlace(p());assert.equal(observer,true);c.aim.from={latitude:36,longitude:140};c.placeSheetFor='aim';c.choosePlace(p());assert.equal(observer,true);c.placeSheetFor='aimTarget';c.choosePlace(p());assert.equal(observer,false);});
test('removing an already-removed clicked record is idempotent and does not report a save error',()=>{const {h}=fixture();h.add('places',p());const row=h.list('places')[0];assert.equal(h.remove('places',row),true);assert.equal(h.remove('places',row),true);assert.equal(h.list('places').length,0);});
