# coding: utf-8
"""Own approximate geometry; no third-party model assets. Units: east,north,up meters.
Dimensions: official tower/deck heights and SKYTREE 68 m equilateral footprint.
PLATEAU 2025 used to check geographic orientation/envelope, not a measured lattice.
Member spacing, thickness, decks' outer profiles and curvature are estimates.
"""
import math,json
from pathlib import Path

def model(name,height):return dict(id=name+'-free-lattice-v1',heightM=height,referenceBearing=0,approximate=True,sourceLabel='自作3D・格子と形状は推定',sourceUrl='https://www.tokyotower.co.jp/guidance/' if name=='tokyotower' else 'https://www.tokyo-skytree.jp/floor/',vertices=[],faces=[],provenance={'kind':'self-authored-approximation','envelopeReference':'PLATEAU 2025 港区・墨田区（参考）','measuredLattice':False})
def add(m,pts):
 i=len(m['vertices']);m['vertices'] += [[round(x,4) for x in p] for p in pts];m['faces'].append(list(range(i,i+len(pts))))
def cross(a,b):return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]
def unit(a):
 l=math.sqrt(sum(x*x for x in a));return [x/l for x in a]
def beam(m,a,b,width):
 direction=unit([b[i]-a[i] for i in range(3)]);u=unit(cross(direction,[0,0,1] if abs(direction[2])<.95 else [1,0,0]));v=cross(direction,u);r=width/2
 add(m,[[p[i]+r*(sx*u[i]+sy*v[i]) for i in range(3)] for p in [a,b] for sx,sy in [(-1,-1),(-1,1),(1,1),(1,-1)]])
def ring(m,h,r,n=24):return [[r*math.sin(i*2*math.pi/n),r*math.cos(i*2*math.pi/n),h] for i in range(n)]
def cylinder(m,z0,z1,r0,r1,n=24):add(m,ring(m,z0,r0,n)+ring(m,z1,r1,n))
def box(m,z0,z1,half0,half1,rot):
 def pts(z,h):return [[x*math.cos(rot)-y*math.sin(rot),x*math.sin(rot)+y*math.cos(rot),z] for x,y in [(-h,-h),(h,-h),(h,h),(-h,h)]]
 add(m,pts(z0,half0)+pts(z1,half1))
def interp(profile,h):
 for (a,x),(b,y) in zip(profile,profile[1:]):
  if a<=h<=b:return x+(y-x)*(h-a)/(b-a)
 return profile[-1][1]

t=model('tokyotower',333);rot=math.pi/4
# Estimated curved four-legged envelope, calibrated to official overall/deck heights.
profile=[(0,47.5),(20,39),(40,29),(60,23),(80,18.5),(100,15),(130,12),(140,11.2),(160,10),(200,7),(245,4.8),(260,3.0),(300,2.2)]
def square(h):
 r=interp(profile,h);return [[x*math.cos(rot)-y*math.sin(rot),x*math.sin(rot)+y*math.cos(rot),h] for x,y in [(-r,-r),(r,-r),(r,r),(-r,r)]]
levels=list(range(0,141,10))+[155]+list(range(160,241,10))+[245,254,260,270,280,290,300]
for a,b in zip(levels,levels[1:]):
 if a==140 or a==245:continue
 low,up=square(a),square(b);w=1.3 if a<80 else .65 if a<245 else .35
 for i in range(4):
  n=(i+1)%4;beam(t,low[i],up[i],w);beam(t,low[i],low[n],w*.7)
  beam(t,low[i],up[n],w*.55);beam(t,low[n],up[i],w*.55)
box(t,0,17,24,24,rot);box(t,140,150,15,15,rot);box(t,150,155,15,12,rot)
box(t,245,250,6,6,rot);box(t,250,254,6,4,rot)
box(t,17,140,1.4,1.4,rot);box(t,155,245,1.0,1.0,rot)
cylinder(t,300,315,2.2,1.0,12);cylinder(t,315,333,.55,.3,12)

s=model('skytree',634)
# 68 m equilateral base morphing continuously toward a circular tower body.
base=68/math.sqrt(3)
tri=[[base*math.sin(i*2*math.pi/3),base*math.cos(i*2*math.pi/3)] for i in range(3)]
def contour(h):
 k=min(1,h/320);r=interp([(0,base),(100,31),(200,24),(320,17),(430,16),(460,12),(495,8)],h);pts=[]
 for i in range(12):
  side=i//4;f=(i%4)/4;a,b=tri[side],tri[(side+1)%3];p=[a[j]*(1-f)+b[j]*f for j in range(2)];angle=math.atan2(p[0],p[1]);circle=[base*math.sin(angle),base*math.cos(angle)]
  q=[((1-k)*p[j]+k*circle[j])*r/base for j in range(2)];pts.append(q+[h])
 return pts
levels=list(range(0,321,16))+[329,374]+list(range(390,431,16))+[434,462,478,494]
for a,b in zip(levels,levels[1:]):
 if a==329 or a==434:continue
 low,up=contour(a),contour(b);w=1.5 if a<160 else 1 if a<329 else .65
 for i in range(12):
  n=(i+1)%12;beam(s,low[i],up[i],w if i%4==0 else w*.65);beam(s,low[i],low[n],w*.55)
  beam(s,low[i],up[n],w*.5);beam(s,low[n],up[i],w*.5)
# Central elevator/concrete shaft is opaque; lattice gaps remain around it.
cylinder(s,0,329,4.0,3.3,16);cylinder(s,374,434,3.3,3,16)
for a,b,r0,r1 in [(329,341,17,24),(341,350,24,28),(350,360,28,32),(360,368,32,28),(368,374,28,17),(434,441,16,19),(441,450,19,18),(450,457,18,15),(457,462,15,12)]:cylinder(s,a,b,r0,r1,32)
for a,b,r0,r1 in [(494,500,8,4),(500,525,4,4),(525,530,4,3),(530,557,3,3),(557,563,3,2.5),(563,587,2.5,2.5),(587,592,2.5,2),(592,616,2,2),(616,630,2,2.8),(630,634,2.8,.4)]:cylinder(s,a,b,r0,r1,24)
for m in [t,s]:
 assert all(all(math.isfinite(x) for x in p) for p in m['vertices'])
 assert max(p[2] for p in m['vertices'])==m['heightM']
models={'tokyotower':t,'skytree':s}
out=Path(__file__).resolve().parent.parent/'sorami-tower-models.js'
out.write_text('/* Generated by tools/build-free-towers.py. Own estimated lattice, not surveyed geometry. */\n(function(g){"use strict";const models='+json.dumps(models,ensure_ascii=False,separators=(',',':'))+';if(typeof module!=="undefined"&&module.exports)module.exports=models;else g.SoramiTowerModels=models;})(typeof globalThis!=="undefined"?globalThis:this);\n')
print(out)
